model:
  name: "Salesforce/blip-image-captioning-base"

data:
  train_json: "data/train.json"
  val_json:   "data/val.json"
  train_image_root: "data/images"
  val_image_root:   "data/images"

  max_length: 40
  batch_size: 8
  num_workers: 2

training:
  num_epochs: 30
  lr: 5e-5
  weight_decay: 0.01
  device: "auto"
  grad_clip: 1.0


logging:
  ckpt_dir: "outputs/checkpoints"
  log_every: 50          # in loss mỗi 50 batch
  save_every_epoch: 1
